# Initiate the service
# docker-compose up -d

# Scale up the number of workers to 3
# docker-compose scale worker=3


balancer:
  image: jwilder/nginx-proxy
  ports:
    - "5000:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock

worker:
  image: nlarusso/test-api
  ports:
    - "5000"
#  env_file: server/credentials.env
  environment:
    - VIRTUAL_HOST=localhost
    - VIRTUAL_PORT=5000
#  external_links:
#    - local-postgres9.3.6:postgresql
  volumes:
    - /opt/devops/test-api/:/opt/data_services/test-api
